"""Comprehensive permission catalog for all pages and actions.

This module defines the full set of permissions available in the system,
organized by category with human-readable labels and descriptions.
Used by the admin roles API to expose available permissions for assignment.
"""

from __future__ import annotations

from app.schemas.rbac import PermissionDefinition


def _permission(
    *,
    permission: str,
    resource: str,
    action: str,
    resource_label: str,
    action_label: str,
    description: str,
    category: str,
) -> PermissionDefinition:
    return PermissionDefinition(
        permission=permission,
        resource=resource,
        action=action,
        resource_label=resource_label,
        action_label=action_label,
        description=description,
        category=category,
    )


PERMISSION_CATALOG: list[PermissionDefinition] = [
    # ─── Core ────────────────────────────────────────────────────────────────
    _permission(
        permission="dashboard:view",
        resource="dashboard",
        action="view",
        resource_label="Dashboard",
        action_label="View",
        description="View the main dashboard overview",
        category="Core",
    ),
    _permission(
        permission="dashboard:edit",
        resource="dashboard",
        action="edit",
        resource_label="Dashboard",
        action_label="Edit",
        description="Customize dashboard widgets and layout",
        category="Core",
    ),
    _permission(
        permission="profile:view",
        resource="profile",
        action="view",
        resource_label="Profile",
        action_label="View",
        description="View personal profile settings and preferences",
        category="Core",
    ),
    _permission(
        permission="profile:edit",
        resource="profile",
        action="edit",
        resource_label="Profile",
        action_label="Edit",
        description="Update personal profile settings and preferences",
        category="Core",
    ),
    # ─── Security ────────────────────────────────────────────────────────────
    _permission(
        permission="detections:view",
        resource="detections",
        action="view",
        resource_label="Detections",
        action_label="View",
        description="View security detections and findings",
        category="Security",
    ),
    _permission(
        permission="detections:edit",
        resource="detections",
        action="edit",
        resource_label="Detections",
        action_label="Edit",
        description="Update detection metadata and triage state",
        category="Security",
    ),
    _permission(
        permission="detections:assign",
        resource="detections",
        action="assign",
        resource_label="Detections",
        action_label="Assign",
        description="Assign detections to users or teams",
        category="Security",
    ),
    _permission(
        permission="detections:dismiss",
        resource="detections",
        action="dismiss",
        resource_label="Detections",
        action_label="Dismiss",
        description="Dismiss detections that have been reviewed",
        category="Security",
    ),
    _permission(
        permission="detections:export",
        resource="detections",
        action="export",
        resource_label="Detections",
        action_label="Export",
        description="Export detections for reporting or analysis",
        category="Security",
    ),
    _permission(
        permission="events:view",
        resource="events",
        action="view",
        resource_label="Events",
        action_label="View",
        description="View security and platform events",
        category="Security",
    ),
    _permission(
        permission="events:edit",
        resource="events",
        action="edit",
        resource_label="Events",
        action_label="Edit",
        description="Annotate or update event metadata",
        category="Security",
    ),
    _permission(
        permission="events:assign",
        resource="events",
        action="assign",
        resource_label="Events",
        action_label="Assign",
        description="Assign events to users or teams for follow-up",
        category="Security",
    ),
    _permission(
        permission="events:dismiss",
        resource="events",
        action="dismiss",
        resource_label="Events",
        action_label="Dismiss",
        description="Dismiss events that do not require action",
        category="Security",
    ),
    _permission(
        permission="events:export",
        resource="events",
        action="export",
        resource_label="Events",
        action_label="Export",
        description="Export event data for reporting or investigation",
        category="Security",
    ),
    _permission(
        permission="posture:view",
        resource="posture",
        action="view",
        resource_label="Security Posture",
        action_label="View",
        description="View posture trends, controls, and recommendations",
        category="Security",
    ),
    _permission(
        permission="posture:edit",
        resource="posture",
        action="edit",
        resource_label="Security Posture",
        action_label="Edit",
        description="Update posture baselines and remediation settings",
        category="Security",
    ),
    _permission(
        permission="posture:export",
        resource="posture",
        action="export",
        resource_label="Security Posture",
        action_label="Export",
        description="Export posture data and remediation plans",
        category="Security",
    ),
    _permission(
        permission="advanced_security:view",
        resource="advanced_security",
        action="view",
        resource_label="Advanced Security",
        action_label="View",
        description="View GitHub Advanced Security insights and coverage",
        category="Security",
    ),
    _permission(
        permission="advanced_security:edit",
        resource="advanced_security",
        action="edit",
        resource_label="Advanced Security",
        action_label="Edit",
        description="Adjust Advanced Security settings and workflows",
        category="Security",
    ),
    _permission(
        permission="advanced_security:export",
        resource="advanced_security",
        action="export",
        resource_label="Advanced Security",
        action_label="Export",
        description="Export Advanced Security findings and metrics",
        category="Security",
    ),
    _permission(
        permission="workflow_security:view",
        resource="workflow_security",
        action="view",
        resource_label="Workflow Security",
        action_label="View",
        description="View workflow security risk and exposure data",
        category="Security",
    ),
    _permission(
        permission="workflow_security:edit",
        resource="workflow_security",
        action="edit",
        resource_label="Workflow Security",
        action_label="Edit",
        description="Update workflow security settings and remediation actions",
        category="Security",
    ),
    _permission(
        permission="workflow_security:export",
        resource="workflow_security",
        action="export",
        resource_label="Workflow Security",
        action_label="Export",
        description="Export workflow security findings and trends",
        category="Security",
    ),
    _permission(
        permission="workflow_health:view",
        resource="workflow_health",
        action="view",
        resource_label="Workflow Health",
        action_label="View",
        description="View workflow reliability, usage, and health metrics",
        category="Security",
    ),
    _permission(
        permission="workflow_health:edit",
        resource="workflow_health",
        action="edit",
        resource_label="Workflow Health",
        action_label="Edit",
        description="Manage workflow health configurations and thresholds",
        category="Security",
    ),
    _permission(
        permission="workflow_health:export",
        resource="workflow_health",
        action="export",
        resource_label="Workflow Health",
        action_label="Export",
        description="Export workflow health trends and reports",
        category="Security",
    ),
    _permission(
        permission="supply_chain:view",
        resource="supply_chain",
        action="view",
        resource_label="Supply Chain",
        action_label="View",
        description="View software supply chain risk and dependency insights",
        category="Security",
    ),
    _permission(
        permission="supply_chain:edit",
        resource="supply_chain",
        action="edit",
        resource_label="Supply Chain",
        action_label="Edit",
        description="Manage supply chain configurations and remediation actions",
        category="Security",
    ),
    _permission(
        permission="supply_chain:export",
        resource="supply_chain",
        action="export",
        resource_label="Supply Chain",
        action_label="Export",
        description="Export supply chain findings and package risk data",
        category="Security",
    ),
    _permission(
        permission="packages:view",
        resource="packages",
        action="view",
        resource_label="Packages",
        action_label="View",
        description="View package inventory and package security insights",
        category="Security",
    ),
    _permission(
        permission="packages:edit",
        resource="packages",
        action="edit",
        resource_label="Packages",
        action_label="Edit",
        description="Manage package settings and remediation workflows",
        category="Security",
    ),
    _permission(
        permission="packages:delete",
        resource="packages",
        action="delete",
        resource_label="Packages",
        action_label="Delete",
        description="Delete or remove managed package records",
        category="Security",
    ),
    _permission(
        permission="threat_intel:view",
        resource="threat_intel",
        action="view",
        resource_label="Threat Intelligence",
        action_label="View",
        description="View curated threat intelligence and attack trends",
        category="Security",
    ),
    _permission(
        permission="threat_intel:edit",
        resource="threat_intel",
        action="edit",
        resource_label="Threat Intelligence",
        action_label="Edit",
        description="Manage threat intelligence feeds and mappings",
        category="Security",
    ),
    _permission(
        permission="threat_intel:export",
        resource="threat_intel",
        action="export",
        resource_label="Threat Intelligence",
        action_label="Export",
        description="Export threat intelligence data and indicators",
        category="Security",
    ),
    _permission(
        permission="playbooks:view",
        resource="playbooks",
        action="view",
        resource_label="Playbooks",
        action_label="View",
        description="View response playbooks and automation steps",
        category="Security",
    ),
    _permission(
        permission="playbooks:edit",
        resource="playbooks",
        action="edit",
        resource_label="Playbooks",
        action_label="Edit",
        description="Modify existing response playbooks",
        category="Security",
    ),
    _permission(
        permission="playbooks:create",
        resource="playbooks",
        action="create",
        resource_label="Playbooks",
        action_label="Create",
        description="Create new response playbooks",
        category="Security",
    ),
    _permission(
        permission="playbooks:delete",
        resource="playbooks",
        action="delete",
        resource_label="Playbooks",
        action_label="Delete",
        description="Delete response playbooks",
        category="Security",
    ),
    _permission(
        permission="playbooks:execute",
        resource="playbooks",
        action="execute",
        resource_label="Playbooks",
        action_label="Execute",
        description="Run response playbooks and automations",
        category="Security",
    ),
    # ─── Platform Intelligence ─────────────────────────────────────────────────
    _permission(
        permission="velocity:view",
        resource="velocity",
        action="view",
        resource_label="Velocity",
        action_label="View",
        description="View engineering velocity metrics and trends",
        category="Platform Intelligence",
    ),
    _permission(
        permission="velocity:edit",
        resource="velocity",
        action="edit",
        resource_label="Velocity",
        action_label="Edit",
        description="Adjust velocity views, goals, and thresholds",
        category="Platform Intelligence",
    ),
    _permission(
        permission="velocity:export",
        resource="velocity",
        action="export",
        resource_label="Velocity",
        action_label="Export",
        description="Export engineering velocity metrics",
        category="Platform Intelligence",
    ),
    _permission(
        permission="dev_activity:view",
        resource="dev_activity",
        action="view",
        resource_label="Developer Activity",
        action_label="View",
        description="View developer activity insights and trends",
        category="Platform Intelligence",
    ),
    _permission(
        permission="dev_activity:edit",
        resource="dev_activity",
        action="edit",
        resource_label="Developer Activity",
        action_label="Edit",
        description="Adjust developer activity views and filters",
        category="Platform Intelligence",
    ),
    _permission(
        permission="dev_activity:export",
        resource="dev_activity",
        action="export",
        resource_label="Developer Activity",
        action_label="Export",
        description="Export developer activity metrics",
        category="Platform Intelligence",
    ),
    _permission(
        permission="user_behavior:view",
        resource="user_behavior",
        action="view",
        resource_label="User Behavior",
        action_label="View",
        description="View user behavior analytics and anomalies",
        category="Platform Intelligence",
    ),
    _permission(
        permission="user_behavior:edit",
        resource="user_behavior",
        action="edit",
        resource_label="User Behavior",
        action_label="Edit",
        description="Manage user behavior baselines and investigations",
        category="Platform Intelligence",
    ),
    _permission(
        permission="user_behavior:export",
        resource="user_behavior",
        action="export",
        resource_label="User Behavior",
        action_label="Export",
        description="Export user behavior analytics and anomalies",
        category="Platform Intelligence",
    ),
    _permission(
        permission="copilot:view",
        resource="copilot",
        action="view",
        resource_label="GitHub Copilot",
        action_label="View",
        description="View GitHub Copilot adoption and usage insights",
        category="Platform Intelligence",
    ),
    _permission(
        permission="copilot:edit",
        resource="copilot",
        action="edit",
        resource_label="GitHub Copilot",
        action_label="Edit",
        description="Manage GitHub Copilot settings and policies",
        category="Platform Intelligence",
    ),
    _permission(
        permission="copilot:export",
        resource="copilot",
        action="export",
        resource_label="GitHub Copilot",
        action_label="Export",
        description="Export GitHub Copilot adoption and usage reports",
        category="Platform Intelligence",
    ),
    _permission(
        permission="org_health:view",
        resource="org_health",
        action="view",
        resource_label="Organization Health",
        action_label="View",
        description="View organization health metrics and insights",
        category="Platform Intelligence",
    ),
    _permission(
        permission="org_health:edit",
        resource="org_health",
        action="edit",
        resource_label="Organization Health",
        action_label="Edit",
        description="Manage organization health views and thresholds",
        category="Platform Intelligence",
    ),
    _permission(
        permission="org_health:export",
        resource="org_health",
        action="export",
        resource_label="Organization Health",
        action_label="Export",
        description="Export organization health reports and metrics",
        category="Platform Intelligence",
    ),
    _permission(
        permission="cross_org:view",
        resource="cross_org",
        action="view",
        resource_label="Cross-Organization",
        action_label="View",
        description="View cross-organization trends and comparisons",
        category="Platform Intelligence",
    ),
    _permission(
        permission="cross_org:edit",
        resource="cross_org",
        action="edit",
        resource_label="Cross-Organization",
        action_label="Edit",
        description="Manage cross-organization saved views and filters",
        category="Platform Intelligence",
    ),
    _permission(
        permission="cross_org:export",
        resource="cross_org",
        action="export",
        resource_label="Cross-Organization",
        action_label="Export",
        description="Export cross-organization analytics",
        category="Platform Intelligence",
    ),
    # ─── Analytics ────────────────────────────────────────────────────────────
    _permission(
        permission="reports:view",
        resource="reports",
        action="view",
        resource_label="Reports",
        action_label="View",
        description="View reports and scheduled report history",
        category="Analytics",
    ),
    _permission(
        permission="reports:edit",
        resource="reports",
        action="edit",
        resource_label="Reports",
        action_label="Edit",
        description="Edit report definitions and schedules",
        category="Analytics",
    ),
    _permission(
        permission="reports:create",
        resource="reports",
        action="create",
        resource_label="Reports",
        action_label="Create",
        description="Create new reports and scheduled exports",
        category="Analytics",
    ),
    _permission(
        permission="reports:delete",
        resource="reports",
        action="delete",
        resource_label="Reports",
        action_label="Delete",
        description="Delete reports and report schedules",
        category="Analytics",
    ),
    _permission(
        permission="reports:export",
        resource="reports",
        action="export",
        resource_label="Reports",
        action_label="Export",
        description="Export report output and data extracts",
        category="Analytics",
    ),
    _permission(
        permission="reports:share",
        resource="reports",
        action="share",
        resource_label="Reports",
        action_label="Share",
        description="Share reports with other users or teams",
        category="Analytics",
    ),
    _permission(
        permission="compliance:view",
        resource="compliance",
        action="view",
        resource_label="Compliance",
        action_label="View",
        description="View compliance posture, controls, and evidence",
        category="Analytics",
    ),
    _permission(
        permission="compliance:edit",
        resource="compliance",
        action="edit",
        resource_label="Compliance",
        action_label="Edit",
        description="Manage compliance programs, mappings, and evidence",
        category="Analytics",
    ),
    _permission(
        permission="compliance:export",
        resource="compliance",
        action="export",
        resource_label="Compliance",
        action_label="Export",
        description="Export compliance evidence and control status",
        category="Analytics",
    ),
    _permission(
        permission="queries:view",
        resource="queries",
        action="view",
        resource_label="Queries",
        action_label="View",
        description="View saved queries and query history",
        category="Analytics",
    ),
    _permission(
        permission="queries:edit",
        resource="queries",
        action="edit",
        resource_label="Queries",
        action_label="Edit",
        description="Edit saved queries and query metadata",
        category="Analytics",
    ),
    _permission(
        permission="queries:create",
        resource="queries",
        action="create",
        resource_label="Queries",
        action_label="Create",
        description="Create new saved queries",
        category="Analytics",
    ),
    _permission(
        permission="queries:delete",
        resource="queries",
        action="delete",
        resource_label="Queries",
        action_label="Delete",
        description="Delete saved queries",
        category="Analytics",
    ),
    _permission(
        permission="queries:execute",
        resource="queries",
        action="execute",
        resource_label="Queries",
        action_label="Execute",
        description="Run ad hoc and saved queries",
        category="Analytics",
    ),
    _permission(
        permission="queries:export",
        resource="queries",
        action="export",
        resource_label="Queries",
        action_label="Export",
        description="Export query results",
        category="Analytics",
    ),
    # ─── Monitoring ───────────────────────────────────────────────────────────
    _permission(
        permission="telemetry:view",
        resource="telemetry",
        action="view",
        resource_label="Telemetry",
        action_label="View",
        description="View platform telemetry streams and trends",
        category="Monitoring",
    ),
    _permission(
        permission="telemetry:edit",
        resource="telemetry",
        action="edit",
        resource_label="Telemetry",
        action_label="Edit",
        description="Manage telemetry filters, dashboards, and alerts",
        category="Monitoring",
    ),
    _permission(
        permission="telemetry:export",
        resource="telemetry",
        action="export",
        resource_label="Telemetry",
        action_label="Export",
        description="Export telemetry data for analysis",
        category="Monitoring",
    ),
    _permission(
        permission="platform_usage:view",
        resource="platform_usage",
        action="view",
        resource_label="Platform Usage",
        action_label="View",
        description="View platform usage and adoption metrics",
        category="Monitoring",
    ),
    _permission(
        permission="platform_usage:edit",
        resource="platform_usage",
        action="edit",
        resource_label="Platform Usage",
        action_label="Edit",
        description="Manage platform usage views and thresholds",
        category="Monitoring",
    ),
    _permission(
        permission="platform_usage:export",
        resource="platform_usage",
        action="export",
        resource_label="Platform Usage",
        action_label="Export",
        description="Export platform usage reports",
        category="Monitoring",
    ),
    _permission(
        permission="sync_status:view",
        resource="sync_status",
        action="view",
        resource_label="Sync Status",
        action_label="View",
        description="View background sync health and job status",
        category="Monitoring",
    ),
    _permission(
        permission="sync_status:edit",
        resource="sync_status",
        action="edit",
        resource_label="Sync Status",
        action_label="Edit",
        description="Manage sync settings and retry behavior",
        category="Monitoring",
    ),
    _permission(
        permission="audit_log:view",
        resource="audit_log",
        action="view",
        resource_label="Audit Log",
        action_label="View",
        description="View audit log entries and history",
        category="Monitoring",
    ),
    _permission(
        permission="audit_log:edit",
        resource="audit_log",
        action="edit",
        resource_label="Audit Log",
        action_label="Edit",
        description="Manage audit log retention and review workflows",
        category="Monitoring",
    ),
    _permission(
        permission="audit_log:export",
        resource="audit_log",
        action="export",
        resource_label="Audit Log",
        action_label="Export",
        description="Export audit log entries for compliance review",
        category="Monitoring",
    ),
    _permission(
        permission="notifications:view",
        resource="notifications",
        action="view",
        resource_label="Notifications",
        action_label="View",
        description="View system notifications and alert deliveries",
        category="Monitoring",
    ),
    _permission(
        permission="notifications:edit",
        resource="notifications",
        action="edit",
        resource_label="Notifications",
        action_label="Edit",
        description="Manage notification routing and preferences",
        category="Monitoring",
    ),
    _permission(
        permission="notifications:dismiss",
        resource="notifications",
        action="dismiss",
        resource_label="Notifications",
        action_label="Dismiss",
        description="Dismiss notifications that have been acknowledged",
        category="Monitoring",
    ),
    # ─── Administration ───────────────────────────────────────────────────────
    _permission(
        permission="rules:view",
        resource="rules",
        action="view",
        resource_label="Rules",
        action_label="View",
        description="View detection and automation rules",
        category="Administration",
    ),
    _permission(
        permission="rules:edit",
        resource="rules",
        action="edit",
        resource_label="Rules",
        action_label="Edit",
        description="Edit detection and automation rules",
        category="Administration",
    ),
    _permission(
        permission="rules:create",
        resource="rules",
        action="create",
        resource_label="Rules",
        action_label="Create",
        description="Create new detection and automation rules",
        category="Administration",
    ),
    _permission(
        permission="rules:delete",
        resource="rules",
        action="delete",
        resource_label="Rules",
        action_label="Delete",
        description="Delete detection and automation rules",
        category="Administration",
    ),
    _permission(
        permission="rules:execute",
        resource="rules",
        action="execute",
        resource_label="Rules",
        action_label="Execute",
        description="Execute rules for validation or manual runs",
        category="Administration",
    ),
    _permission(
        permission="admin_settings:view",
        resource="admin_settings",
        action="view",
        resource_label="Admin Settings",
        action_label="View",
        description="View administrative settings and configuration",
        category="Administration",
    ),
    _permission(
        permission="admin_settings:edit",
        resource="admin_settings",
        action="edit",
        resource_label="Admin Settings",
        action_label="Edit",
        description="Update administrative settings and configuration",
        category="Administration",
    ),
    _permission(
        permission="admin_users:view",
        resource="admin_users",
        action="view",
        resource_label="Admin Users",
        action_label="View",
        description="View user accounts and access assignments",
        category="Administration",
    ),
    _permission(
        permission="admin_users:edit",
        resource="admin_users",
        action="edit",
        resource_label="Admin Users",
        action_label="Edit",
        description="Edit user account settings and assignments",
        category="Administration",
    ),
    _permission(
        permission="admin_users:create",
        resource="admin_users",
        action="create",
        resource_label="Admin Users",
        action_label="Create",
        description="Create user access assignments",
        category="Administration",
    ),
    _permission(
        permission="admin_users:delete",
        resource="admin_users",
        action="delete",
        resource_label="Admin Users",
        action_label="Delete",
        description="Delete or revoke user access assignments",
        category="Administration",
    ),
    _permission(
        permission="admin_users:assign",
        resource="admin_users",
        action="assign",
        resource_label="Admin Users",
        action_label="Assign",
        description="Assign roles and teams to users",
        category="Administration",
    ),
    _permission(
        permission="admin_roles:view",
        resource="admin_roles",
        action="view",
        resource_label="Admin Roles",
        action_label="View",
        description="View RBAC roles and permissions",
        category="Administration",
    ),
    _permission(
        permission="admin_roles:edit",
        resource="admin_roles",
        action="edit",
        resource_label="Admin Roles",
        action_label="Edit",
        description="Edit RBAC roles and permissions",
        category="Administration",
    ),
    _permission(
        permission="admin_roles:create",
        resource="admin_roles",
        action="create",
        resource_label="Admin Roles",
        action_label="Create",
        description="Create custom RBAC roles",
        category="Administration",
    ),
    _permission(
        permission="admin_roles:delete",
        resource="admin_roles",
        action="delete",
        resource_label="Admin Roles",
        action_label="Delete",
        description="Delete custom RBAC roles",
        category="Administration",
    ),
    _permission(
        permission="admin_roles:assign",
        resource="admin_roles",
        action="assign",
        resource_label="Admin Roles",
        action_label="Assign",
        description="Assign roles to users or teams",
        category="Administration",
    ),
    _permission(
        permission="admin_teams:view",
        resource="admin_teams",
        action="view",
        resource_label="Admin Teams",
        action_label="View",
        description="View team definitions and team access",
        category="Administration",
    ),
    _permission(
        permission="admin_teams:edit",
        resource="admin_teams",
        action="edit",
        resource_label="Admin Teams",
        action_label="Edit",
        description="Edit team definitions and assignments",
        category="Administration",
    ),
    _permission(
        permission="admin_teams:create",
        resource="admin_teams",
        action="create",
        resource_label="Admin Teams",
        action_label="Create",
        description="Create administrative teams",
        category="Administration",
    ),
    _permission(
        permission="admin_teams:delete",
        resource="admin_teams",
        action="delete",
        resource_label="Admin Teams",
        action_label="Delete",
        description="Delete administrative teams",
        category="Administration",
    ),
    _permission(
        permission="admin_teams:assign",
        resource="admin_teams",
        action="assign",
        resource_label="Admin Teams",
        action_label="Assign",
        description="Assign users and roles to teams",
        category="Administration",
    ),
]

PERMISSION_CATEGORIES: list[str] = [
    "Core",
    "Security",
    "Platform Intelligence",
    "Analytics",
    "Monitoring",
    "Administration",
]


def get_catalog() -> list[PermissionDefinition]:
    """Return the full permission catalog."""
    return PERMISSION_CATALOG


def get_categories() -> list[str]:
    """Return available permission categories."""
    return PERMISSION_CATEGORIES
