"""Add retention_policies table with default policies.

Revision ID: 0041
Revises: 0040
Create Date: 2024-01-21 01:00:00.000000+00:00

Creates a ``retention_policies`` table to centralise data retention
configuration.  All managed table retention periods are stored here
instead of being scattered across hardcoded dicts and schema defaults.
"""

from alembic import op

revision = "0041"
down_revision = "0040"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create retention_policies table and seed default policies."""
    op.execute("""
        CREATE TABLE IF NOT EXISTS retention_policies (
            id              SERIAL PRIMARY KEY,
            data_type       TEXT NOT NULL UNIQUE,
            category        TEXT NOT NULL,
            display_name    TEXT NOT NULL,
            description     TEXT NOT NULL,
            retention_days  INTEGER NOT NULL,
            minimum_days    INTEGER NOT NULL,
            is_system       BOOLEAN NOT NULL DEFAULT true,
            updated_by      TEXT,
            updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    """)

    op.execute("""
        INSERT INTO retention_policies
            (data_type, category, display_name, description, retention_days, minimum_days, is_system)
        VALUES
            ('events', 'core_data', 'Audit Events',
             'GitHub audit log events ingested from the enterprise',
             365, 90, true),
            ('raw_payloads', 'core_data', 'Raw Payloads',
             'Original JSON payloads stored for forensic analysis',
             90, 7, true),
            ('detections', 'core_data', 'Detections',
             'Security detections generated by the detection pipeline',
             365, 30, true),
            ('event_dedup', 'core_data', 'Event Deduplication',
             'Short-lived deduplication records to prevent duplicate ingestion',
             7, 1, true),
            ('audit_trail', 'system', 'Audit Trail',
             'Internal audit trail of administrative actions',
             730, 365, true),
            ('enterprise_sync_log', 'system', 'Enterprise Sync Log',
             'Sync operation logs for enterprise data synchronisation',
             90, 7, true),
            ('system_health_events', 'system', 'System Health Events',
             'Internal system health and monitoring events',
             90, 7, true),
            ('behavioral_baselines', 'analytics', 'Behavioral Baselines',
             'Computed behavioral baselines used by anomaly detection rules',
             180, 30, true),
            ('copilot_metrics', 'analytics', 'Copilot Metrics',
             'GitHub Copilot usage and adoption metrics',
             365, 30, true),
            ('report_history', 'analytics', 'Report History',
             'Generated report snapshots and export history',
             180, 7, true),
            ('notification_history', 'system', 'Notification History',
             'Outbound notification delivery records',
             90, 7, true)
        ON CONFLICT (data_type) DO NOTHING
    """)


def downgrade() -> None:
    """Drop retention_policies table."""
    op.execute("DROP TABLE IF EXISTS retention_policies")
