#cloud-config
# OctoWatch Management VM Bootstrap — Ubuntu 24.04 LTS
# Purpose: K8s admin bastion, CI runner, etcd backup, SSH jump host
# Generated by Terraform — do not edit on the VM.

package_update: true
package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - jq
  - git
  - unzip
  - postgresql-client

write_files:

  # ── SSH hardening ─────────────────────────────────────────────────────────
  - path: /etc/ssh/sshd_config.d/99-octowatch.conf
    owner: root:root
    permissions: '0600'
    content: |
      PasswordAuthentication no
      PermitRootLogin no
      PubkeyAuthentication yes
      MaxAuthTries 3
      LoginGraceTime 30
      ClientAliveInterval 300
      ClientAliveCountMax 2
      X11Forwarding no
      AllowAgentForwarding yes
      AllowTcpForwarding yes

  # ── SSH config for cluster nodes ──────────────────────────────────────────
  - path: /home/octowatch/.ssh/config
    owner: octowatch:octowatch
    permissions: '0600'
    content: |
      # K8s cluster nodes — accessible from this management VM
%{ for i, ip in k8s_node_ips }
      Host k8s-node-${i}
        HostName ${ip}
        User octowatch
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null
%{ endfor }

      Host 10.0.8.*
        User octowatch
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null

  # ── etcd backup script ────────────────────────────────────────────────────
  - path: /usr/local/bin/etcd-backup.sh
    owner: root:root
    permissions: '0700'
    content: |
      #!/usr/bin/env bash
      # etcd backup via kubectl exec into the etcd static pod
      set -euo pipefail

      KUBECONFIG="/home/octowatch/.kube/config"
      STORAGE_ACCOUNT="${storage_account_name}"
      STORAGE_KEY="${storage_account_key}"
      CONTAINER="etcd-backups"
      TIMESTAMP=$(date +%Y%m%d-%H%M%S)
      SNAPSHOT_FILE="/tmp/etcd-snapshot-$${TIMESTAMP}.db"
      NODE_NAME="k8s-node-0"
      ETCD_POD="etcd-$${NODE_NAME}"

      echo "[$(date)] Starting etcd backup..."

      # Snapshot etcd via kubectl exec
      kubectl --kubeconfig="$KUBECONFIG" exec -n kube-system "$ETCD_POD" -- \
        etcdctl snapshot save /tmp/etcd-snapshot.db \
        --cacert=/etc/kubernetes/pki/etcd/ca.crt \
        --cert=/etc/kubernetes/pki/etcd/server.crt \
        --key=/etc/kubernetes/pki/etcd/server.key

      # Copy snapshot out of the pod
      kubectl --kubeconfig="$KUBECONFIG" cp \
        "kube-system/$${ETCD_POD}:/tmp/etcd-snapshot.db" \
        "$SNAPSHOT_FILE"

      # Upload to Azure Blob
      az storage blob upload \
        --account-name "$STORAGE_ACCOUNT" \
        --account-key "$STORAGE_KEY" \
        --container-name "$CONTAINER" \
        --name "etcd-snapshot-$${TIMESTAMP}.db" \
        --file "$SNAPSHOT_FILE" \
        --overwrite \
        --only-show-errors

      # Cleanup
      rm -f "$SNAPSHOT_FILE"
      kubectl --kubeconfig="$KUBECONFIG" exec -n kube-system "$ETCD_POD" -- \
        rm -f /tmp/etcd-snapshot.db

      # Prune backups older than 14 days
      CUTOFF=$(date -d "-14 days" +%Y%m%d 2>/dev/null || date -v-14d +%Y%m%d)
      az storage blob list \
        --account-name "$STORAGE_ACCOUNT" \
        --account-key "$STORAGE_KEY" \
        --container-name "$CONTAINER" \
        --query "[?properties.creationTime < '$${CUTOFF}'].name" \
        --output tsv \
        --only-show-errors | while read -r blob; do
          echo "Pruning old backup: $blob"
          az storage blob delete \
            --account-name "$STORAGE_ACCOUNT" \
            --account-key "$STORAGE_KEY" \
            --container-name "$CONTAINER" \
            --name "$blob" \
            --only-show-errors
        done

      echo "[$(date)] etcd backup complete: etcd-snapshot-$${TIMESTAMP}.db"

  # ── kubeconfig fetch script ───────────────────────────────────────────────
  - path: /usr/local/bin/fetch-kubeconfig.sh
    owner: root:root
    permissions: '0700'
    content: |
      #!/usr/bin/env bash
      # Download kubeconfig from Azure Blob (uploaded by control-plane cloud-init)
      set -euo pipefail

      STORAGE_ACCOUNT="${storage_account_name}"
      STORAGE_KEY="${storage_account_key}"
      KUBECONFIG_DIR="/home/octowatch/.kube"
      KUBECONFIG_FILE="$KUBECONFIG_DIR/config"

      echo "Fetching kubeconfig from Azure Blob..."
      mkdir -p "$KUBECONFIG_DIR"

      for i in $(seq 1 90); do
        az storage blob download \
          --account-name "$STORAGE_ACCOUNT" \
          --account-key "$STORAGE_KEY" \
          --container-name "k8s-bootstrap" \
          --name "admin.conf" \
          --file "$KUBECONFIG_FILE" \
          --only-show-errors 2>/dev/null && break
        echo "Waiting for kubeconfig ($i/90)..."
        sleep 10
      done

      if [ ! -f "$KUBECONFIG_FILE" ]; then
        echo "ERROR: kubeconfig not available after 15 minutes"
        exit 1
      fi

      chown octowatch:octowatch "$KUBECONFIG_DIR" "$KUBECONFIG_FILE"
      chmod 600 "$KUBECONFIG_FILE"
      echo "kubeconfig installed at $KUBECONFIG_FILE"

      # Delete bootstrap artifacts from blob (security: don't leave admin.conf accessible)
      az storage blob delete \
        --account-name "$STORAGE_ACCOUNT" \
        --account-key "$STORAGE_KEY" \
        --container-name "k8s-bootstrap" \
        --name "admin.conf" \
        --only-show-errors 2>/dev/null || true
      az storage blob delete \
        --account-name "$STORAGE_ACCOUNT" \
        --account-key "$STORAGE_KEY" \
        --container-name "k8s-bootstrap" \
        --name "join-command.txt" \
        --only-show-errors 2>/dev/null || true
      echo "Bootstrap artifacts cleaned from blob storage."

  # ── GHCR pull secret creation script ──────────────────────────────────────
  - path: /usr/local/bin/create-pull-secret.sh
    owner: root:root
    permissions: '0700'
    content: |
      #!/usr/bin/env bash
      # Create GHCR pull secret in the octowatch namespace
      set -euo pipefail
      KUBECONFIG="/home/octowatch/.kube/config"

      kubectl --kubeconfig="$KUBECONFIG" create namespace octowatch 2>/dev/null || true

      kubectl --kubeconfig="$KUBECONFIG" create secret docker-registry ghcr-pull-secret \
        --namespace=octowatch \
        --docker-server=ghcr.io \
        --docker-username="${ghcr_username}" \
        --docker-password="${ghcr_token}" \
        --dry-run=client -o yaml | \
        kubectl --kubeconfig="$KUBECONFIG" apply -f -

      echo "GHCR pull secret created in octowatch namespace."

runcmd:

  # ── Install Azure CLI ─────────────────────────────────────────────────────
  - |
    curl -sL https://aka.ms/InstallAzureCLIDeb | bash

  # ── Install kubectl ───────────────────────────────────────────────────────
  - |
    curl -fsSL "https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key" | \
      gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] \
      https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /" \
      > /etc/apt/sources.list.d/kubernetes.list
    apt-get update
    apt-get install -y kubectl
    apt-mark hold kubectl

  # ── Install Helm ──────────────────────────────────────────────────────────
  - |
    curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

  # ── Fetch kubeconfig from Azure Blob ──────────────────────────────────────
  - /usr/local/bin/fetch-kubeconfig.sh

  # ── Create GHCR pull secret ───────────────────────────────────────────────
  - /usr/local/bin/create-pull-secret.sh

  # ── Add Helm repos ────────────────────────────────────────────────────────
  - |
    su - octowatch -c "
      helm repo add jetstack https://charts.jetstack.io
      helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      helm repo update
    "

  # ── Setup etcd backup cron (daily at 3 AM UTC) ───────────────────────────
  - |
    echo "0 3 * * * root /usr/local/bin/etcd-backup.sh >> /var/log/etcd-backup.log 2>&1" \
      > /etc/cron.d/etcd-backup
    chmod 0644 /etc/cron.d/etcd-backup

  # ── Wait for all K8s nodes to be Ready ─────────────────────────────────
  - |
    KUBECONFIG="/home/octowatch/.kube/config"
    echo "Waiting for all K8s nodes to be Ready..."
    READY_COUNT=0
    for i in $(seq 1 60); do
      READY_COUNT=$(kubectl --kubeconfig="$KUBECONFIG" get nodes --no-headers 2>/dev/null | grep -c ' Ready' || true)
      READY_COUNT=$${READY_COUNT:-0}
      echo "  Ready nodes: $READY_COUNT/3 (attempt $i/60)"
      [ "$READY_COUNT" -ge 3 ] 2>/dev/null && break
      sleep 15
    done
    if [ "$READY_COUNT" -lt 3 ] 2>/dev/null; then
      echo "WARNING: Not all nodes Ready after 15 minutes. Continuing anyway..."
    fi

  # ── Install local-path-provisioner (Rancher) ───────────────────────────
  - |
    KUBECONFIG="/home/octowatch/.kube/config"
    echo "Installing local-path-provisioner..."

    # Download and patch the manifest to use /mnt/octowatch-data
    curl -fsSL https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.30/deploy/local-path-storage.yaml \
      | sed 's|/opt/local-path-provisioner|/mnt/octowatch-data|g' \
      | kubectl --kubeconfig="$KUBECONFIG" apply -f -

    # Make local-path the default StorageClass
    kubectl --kubeconfig="$KUBECONFIG" patch storageclass local-path \
      -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'

    echo "local-path-provisioner installed (path: /mnt/octowatch-data)"

  # ── Install cert-manager ───────────────────────────────────────────────
  - |
    su - octowatch -c "
      helm install cert-manager jetstack/cert-manager \
        --namespace cert-manager --create-namespace \
        --set crds.enabled=true \
        --wait --timeout 5m
    "
    echo "cert-manager installed."

  # ── Create Let's Encrypt ClusterIssuer ─────────────────────────────────
  - |
    KUBECONFIG="/home/octowatch/.kube/config"
    cat <<'ISSUER_EOF' | kubectl --kubeconfig="$KUBECONFIG" apply -f -
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: letsencrypt-prod
    spec:
      acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: ${environment}@octowatch.dev
        privateKeySecretRef:
          name: letsencrypt-prod
        solvers:
          - http01:
              ingress:
                class: nginx
    ISSUER_EOF
    echo "ClusterIssuer letsencrypt-prod created."

  # ── Install ingress-nginx (DaemonSet + hostPort mode) ──────────────────
  - |
    su - octowatch -c "
      helm install ingress-nginx ingress-nginx/ingress-nginx \
        --namespace ingress-nginx --create-namespace \
        --set controller.kind=DaemonSet \
        --set controller.hostPort.enabled=true \
        --set controller.service.enabled=false \
        --set controller.ingressClassResource.default=true \
        --wait --timeout 5m
    "
    echo "ingress-nginx installed (DaemonSet, hostPort 80/443)."

  # ── Setup unattended-upgrades ─────────────────────────────────────────────
  - |
    apt-get install -y unattended-upgrades
    dpkg-reconfigure -plow unattended-upgrades

final_message: "OctoWatch management VM bootstrap complete."
