#cloud-config
# OctoWatch cloud-init bootstrap for Ubuntu 24.04 LTS
# Environment: ${environment}
# Generated by Terraform -- do not edit on the VM.

package_update: true
package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - jq
  - git
  - unzip
  - python3-pip
  - certbot
  - postgresql-client

write_files:

  # -- Docker daemon configuration ----------------------------------------------
  # - JSON log driver with rotation (max 100 MB x 3 files)
  # - live-restore: containers keep running during daemon upgrades
  # - userns-remap: run containers as unprivileged user namespace (defence-in-depth)
  # - no-new-privileges: prevent privilege escalation inside containers
  - path: /etc/docker/daemon.json
    owner: root:root
    permissions: '0644'
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m",
          "max-file": "3"
        },
        "live-restore": true,
        "no-new-privileges": true
      }

  # -- SSH hardening -------------------------------------------------------------
  - path: /etc/ssh/sshd_config.d/99-octowatch.conf
    owner: root:root
    permissions: '0600'
    content: |
      # OctoWatch SSH hardening -- managed by cloud-init
      PasswordAuthentication no
      PermitRootLogin no
      PubkeyAuthentication yes
      AuthorizedKeysFile .ssh/authorized_keys
      MaxAuthTries 3
      LoginGraceTime 30
      ClientAliveInterval 300
      ClientAliveCountMax 2
      X11Forwarding no
      AllowAgentForwarding no
      AllowTcpForwarding no
      PermitTunnel no
      Banner none

  # -- Systemd service unit ------------------------------------------------------
  # Starts the Docker Compose stack on boot after docker.service is ready.
  - path: /etc/systemd/system/octowatch.service
    owner: root:root
    permissions: '0644'
    content: |
      [Unit]
      Description=OctoWatch Docker Compose Stack
      Documentation=https://github.com/${ghcr_owner}/octowatch
      Requires=docker.service
      After=docker.service network-online.target

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      WorkingDirectory=/opt/octowatch/compose
      ExecStart=/usr/bin/docker compose up -d --remove-orphans
      ExecStop=/usr/bin/docker compose down --timeout 30
      User=root
      StandardOutput=journal
      StandardError=journal
      TimeoutStartSec=300

      [Install]
      WantedBy=multi-user.target

  # -- PostgreSQL backup script --------------------------------------------------
  # Runs from cron (daily at 03:00 UTC). Uses managed identity for Azure auth.
  # Requires: pg_dump installed (postgresql-client package), az CLI.
  - path: /opt/octowatch/scripts/backup-azure.sh
    owner: root:root
    permissions: '0750'
    content: |
      #!/bin/bash
      # OctoWatch -- PostgreSQL backup to Azure Blob Storage
      # Authenticates via VM managed identity (no stored credentials).
      set -eu

      STORAGE_ACCOUNT="${storage_account_name}"
      CONTAINER="pg-backups"
      LOG_PREFIX="[octowatch-backup]"
      BACKUP_DATE=$(date +%Y%m%d-%H%M%S)
      BLOB_PATH="$(date +%Y/%m/%d)/$BACKUP_DATE.sql.gz"
      BACKUP_FILE="/tmp/octowatch-$BACKUP_DATE.sql.gz"

      echo "$LOG_PREFIX Starting backup: $BACKUP_DATE"

      # Load application environment (DATABASE_URL etc.)
      if [ -f /opt/octowatch/compose/.env ]; then
        set -a
        # shellcheck disable=SC1091
        . /opt/octowatch/compose/.env
        set +a
      else
        echo "$LOG_PREFIX ERROR: .env file not found" >&2
        exit 1
      fi

      if [ -z "$${DATABASE_URL:-}" ]; then
        echo "$LOG_PREFIX ERROR: DATABASE_URL is not set" >&2
        exit 1
      fi

      # Dump the PostgreSQL database and compress inline.
      echo "$LOG_PREFIX Dumping database..."
      # Strip SQLAlchemy driver prefix (pg_dump needs plain postgresql:// URL).
      PG_DUMP_URL=$(echo "$DATABASE_URL" | sed 's|postgresql+asyncpg://|postgresql://|')
      pg_dump "$PG_DUMP_URL" | gzip > "$BACKUP_FILE"
      BACKUP_SIZE=$(du -sh "$BACKUP_FILE" | cut -f1)
      echo "$LOG_PREFIX Dump complete: $BACKUP_SIZE"

      # Upload to Azure Blob Storage using managed identity.
      echo "$LOG_PREFIX Uploading to Azure Blob Storage: $BLOB_PATH"
      az storage blob upload \
        --account-name "$STORAGE_ACCOUNT" \
        --container-name "$CONTAINER" \
        --name "$BLOB_PATH" \
        --file "$BACKUP_FILE" \
        --account-key "${storage_account_key}" \
        --overwrite

      # Clean up local temp file.
      rm -f "$BACKUP_FILE"

      echo "$LOG_PREFIX Backup completed successfully: gs://$STORAGE_ACCOUNT/$CONTAINER/$BLOB_PATH"

  # -- nginx.conf (base64-encoded from repo source) ------------------------------
  - path: /opt/octowatch/nginx/nginx.conf
    owner: root:root
    permissions: '0644'
    encoding: b64
    content: ${nginx_conf_b64}

  # -- docker-compose.yml (base64-encoded, GHCR images + bind-mount volumes) -----
  # The compose file has been modified from the repo source:
  #   - Image names updated to ghcr.io/${ghcr_owner}/octowatch-*:${ghcr_image_tag}
  #   - Top-level volumes replaced with bind-mount entries pointing to the data disk
  #   - nginx volume paths updated to absolute host paths
  - path: /opt/octowatch/compose/docker-compose.yml
    owner: root:root
    permissions: '0644'
    encoding: b64
    content: ${compose_b64}

  # -- .env file (base64-encoded secrets, rendered by Terraform at apply time) ----
  # Avoids placing KEY=VALUE lines directly in the YAML literal block, which
  # would confuse the YAML parser due to zero-indent heredoc content.
  - path: /opt/octowatch/compose/.env
    owner: root:root
    permissions: '0600'
    encoding: b64
    content: ${env_file_b64}

  # -- GHCR token (written here so Step 9 runcmd can docker login) ---------------
  - path: /opt/octowatch/.ghcr_token
    owner: root:root
    permissions: '0600'
    content: ${ghcr_token}

  # -- Let's Encrypt renewal script -----------------------------------------------
  # Written here (not via heredoc in runcmd) because file content at column-0
  # inside a YAML literal block scalar causes the YAML parser to exit the block.
  - path: /opt/octowatch/scripts/renew-cert.sh
    owner: root:root
    permissions: '0755'
    content: |
      #!/bin/bash
      # OctoWatch -- Let's Encrypt renewal script
      # Stops nginx to free port 80, renews cert, copies files, restarts nginx.
      set -eu
      DOMAIN=$(certbot certificates 2>/dev/null | grep "Domains:" | head -1 | awk '{print $2}')
      SSL_DIR="/opt/octowatch/ssl"
      cd /opt/octowatch/compose
      docker compose stop nginx
      certbot renew --standalone --quiet
      if certbot certificates 2>/dev/null | grep -q "VALID"; then
        cp "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" "$SSL_DIR/cert.pem"
        cp "/etc/letsencrypt/live/$DOMAIN/privkey.pem"   "$SSL_DIR/key.pem"
        chmod 644 "$SSL_DIR/cert.pem" "$SSL_DIR/key.pem"
      fi
      docker compose start nginx

  # -- Daily PostgreSQL backup cron -----------------------------------------------
  - path: /etc/cron.d/octowatch-backup
    owner: root:root
    permissions: '0644'
    content: |
      # OctoWatch -- daily PostgreSQL backup to Azure Blob Storage
      0 3 * * * root /opt/octowatch/scripts/backup-azure.sh >> /var/log/octowatch-backup.log 2>&1

  # -- Let's Encrypt renewal cron (twice daily per certbot best practice) ----------
  - path: /etc/cron.d/octowatch-certbot
    owner: root:root
    permissions: '0644'
    content: |
      # OctoWatch -- Let's Encrypt renewal check
      0 */12 * * * root /opt/octowatch/scripts/renew-cert.sh >> /var/log/letsencrypt/renewal.log 2>&1

runcmd:

  # -- Step 1: Install Docker CE from the official apt repository ----------------
  # We install docker-ce (not docker.io) to get the latest stable release with
  # compose plugin support.
  - |
    set -eu
    echo "[cloud-init] Installing Docker CE..."
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
      -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc
    ARCH=$(dpkg --print-architecture)
    CODENAME=$(. /etc/os-release && echo "$VERSION_CODENAME")
    echo "deb [arch=$ARCH signed-by=/etc/apt/keyrings/docker.asc] \
    https://download.docker.com/linux/ubuntu $CODENAME stable" \
      > /etc/apt/sources.list.d/docker.list
    apt-get update -qq
    apt-get install -y \
      docker-ce \
      docker-ce-cli \
      containerd.io \
      docker-buildx-plugin \
      docker-compose-plugin
    systemctl enable docker
    systemctl start docker
    echo "[cloud-init] Docker CE installed: $(docker --version)"

  # -- Step 2: Install Azure CLI -------------------------------------------------
  - |
    set -eu
    echo "[cloud-init] Installing Azure CLI..."
    curl -sL https://aka.ms/InstallAzureCLIDeb | bash
    echo "[cloud-init] Azure CLI installed: $(az --version | head -1)"

  # -- Step 3: Create octowatch system user and add to docker group --------------
  - |
    set -eu
    echo "[cloud-init] Creating octowatch user..."
    if ! id octowatch >/dev/null 2>&1; then
      useradd \
        --system \
        --create-home \
        --home-dir /home/octowatch \
        --shell /bin/bash \
        --comment "OctoWatch service account" \
        octowatch
    fi
    usermod -aG docker octowatch
    echo "[cloud-init] User octowatch created and added to docker group."

  # -- Step 4: Create application directory structure ----------------------------
  - |
    set -eu
    echo "[cloud-init] Creating directory structure..."
    mkdir -p \
      /opt/octowatch/compose \
      /opt/octowatch/nginx \
      /opt/octowatch/ssl \
      /opt/octowatch/certbot-webroot \
      /opt/octowatch/scripts
    # Data disk subdirectories (will exist after disk mount in Step 5)
    # Created here as placeholders; Step 5 recreates them on the mounted volume.
    mkdir -p \
      /mnt/octowatch-data/pg_data \
      /mnt/octowatch-data/valkey_data
    chown -R octowatch:octowatch /opt/octowatch
    chmod 750 /opt/octowatch/scripts
    echo "[cloud-init] Directory structure created."

  # -- Step 5: Format and mount data disk ---------------------------------------
  # Azure attaches the first data disk (LUN 0) via /dev/disk/azure/scsi1/lun0.
  # We resolve the symlink to get the actual device (sdb, sdc, etc.) which
  # varies by VM size. Format ext4 and add a permanent fstab entry with nofail.
  - |
    set -eu
    # Use the stable Azure disk symlink instead of hardcoded /dev/sdX
    AZURE_DISK_SYMLINK="/dev/disk/azure/scsi1/lun0"
    MOUNT_POINT="/mnt/octowatch-data"
    echo "[cloud-init] Resolving data disk from Azure LUN 0 symlink..."

    # Wait up to 60 seconds for the symlink to appear (udev timing).
    WAITED=0
    while [ ! -L "$AZURE_DISK_SYMLINK" ] && [ $WAITED -lt 60 ]; do
      echo "[cloud-init] Waiting for $AZURE_DISK_SYMLINK... ($WAITED s)"
      sleep 5
      WAITED=$((WAITED + 5))
    done

    if [ ! -L "$AZURE_DISK_SYMLINK" ]; then
      echo "[cloud-init] ERROR: Azure disk symlink $AZURE_DISK_SYMLINK not found after 60s" >&2
      exit 1
    fi

    DATA_DISK=$(readlink -f "$AZURE_DISK_SYMLINK")
    echo "[cloud-init] Data disk resolved to: $DATA_DISK"

    # Format only if the disk has no filesystem (idempotent).
    FS_TYPE=$(blkid -o value -s TYPE "$DATA_DISK" 2>/dev/null || echo "")
    if [ -z "$FS_TYPE" ]; then
      echo "[cloud-init] Formatting $DATA_DISK as ext4..."
      mkfs.ext4 -L octowatch-data -F "$DATA_DISK"
    else
      echo "[cloud-init] $DATA_DISK already has filesystem: $FS_TYPE -- skipping format."
    fi

    # Mount the data disk.
    mkdir -p "$MOUNT_POINT"
    mount "$DATA_DISK" "$MOUNT_POINT"

    # Add fstab entry (nofail ensures boot continues if disk is absent).
    DISK_UUID=$(blkid -s UUID -o value "$DATA_DISK")
    if ! grep -q "$DISK_UUID" /etc/fstab; then
      echo "UUID=$DISK_UUID  $MOUNT_POINT  ext4  defaults,nofail,noatime  0  2" >> /etc/fstab
      echo "[cloud-init] Added fstab entry for UUID=$DISK_UUID"
    fi

    # Create Docker volume bind-mount directories on the data disk.
    mkdir -p \
      "$MOUNT_POINT/pg_data" \
      "$MOUNT_POINT/valkey_data"
    chown -R 999:999 "$MOUNT_POINT/pg_data"   # PostgreSQL UID
    chown -R 999:999 "$MOUNT_POINT/valkey_data"
    chmod 700 "$MOUNT_POINT/pg_data"
    echo "[cloud-init] Data disk mounted at $MOUNT_POINT."

  # -- Step 6: Azure managed identity login (best-effort for backup uploads) -----
  # Secrets are now baked into cloud-init; KV login is not required.
  # The backup script uses storage account key auth, so managed identity is
  # optional. We attempt login but do NOT abort if it fails.
  - |
    set -eu
    echo "[cloud-init] Attempting Azure managed identity login (optional)..."
    for i in 1 2 3 4 5; do
      if az login --identity --username "${managed_identity_client_id}" --output none 2>/dev/null; then
        echo "[cloud-init] Azure login successful."
        break
      fi
      echo "[cloud-init] Azure login attempt $i failed, retrying in 5s..."
      sleep 5
    done
    az account show --output none && echo "[cloud-init] Azure session ready." || echo "[cloud-init] Azure login skipped (not required for this deployment)."

  # -- Step 7: Finalize .env file (set ownership, handle GitHub App key) ---------
  # The .env file was already written by write_files above (b64-encoded).
  # Here we just ensure correct ownership and optionally write the GitHub App key.
  - |
    set -eu
    ENV_FILE="/opt/octowatch/compose/.env"
    chown octowatch:octowatch "$ENV_FILE"
    echo "[cloud-init] .env ownership set."

    # Write GitHub App private key to a dedicated file if provided.
    %{ if secret_github_app_private_key != "" ~}
    KEY_FILE="/opt/octowatch/compose/github-app-key.pem"
    printf '%s\n' '${secret_github_app_private_key}' > "$KEY_FILE"
    chmod 600 "$KEY_FILE"
    chown octowatch:octowatch "$KEY_FILE"
    echo "[cloud-init] GitHub App private key written to $KEY_FILE"
    %{ endif ~}

    echo "[cloud-init] Step 7 complete."

  # -- Step 8: Set correct ownership on compose files ---------------------------
  - |
    set -eu
    chown -R octowatch:octowatch /opt/octowatch/compose
    chown octowatch:octowatch /opt/octowatch/nginx/nginx.conf
    echo "[cloud-init] File ownership set."

  # -- Step 9: Authenticate to GHCR ---------------------------------------------
  - |
    set -eu
    echo "[cloud-init] Logging in to GHCR..."
    GHCR_TOKEN=$(cat /opt/octowatch/.ghcr_token)
    echo "$GHCR_TOKEN" | docker login ghcr.io \
      --username "${ghcr_username}" \
      --password-stdin
    rm -f /opt/octowatch/.ghcr_token
    echo "[cloud-init] GHCR login successful."

  # -- Step 10: TLS certificate provisioning ------------------------------------
  # Mode: ${tls_mode}
  # Domain: ${tls_domain}
  - |
    set -eu
    TLS_MODE="${tls_mode}"
    TLS_DOMAIN="${tls_domain}"
    SSL_DIR="/opt/octowatch/ssl"
    CERTBOT_WEBROOT="/opt/octowatch/certbot-webroot"

    echo "[cloud-init] Provisioning TLS certificates (mode: $TLS_MODE, domain: $TLS_DOMAIN)..."

    if [ "$TLS_MODE" = "letsencrypt" ]; then
      # Let's Encrypt: use certbot standalone authenticator.
      # Standalone mode runs its own temporary HTTP server on port 80 for
      # the ACME challenge -- no nginx needed at this stage.
      CERTBOT_EMAIL="${certbot_email}"
      if [ -z "$CERTBOT_EMAIL" ]; then
        echo "[cloud-init] ERROR: certbot_email is required for letsencrypt mode" >&2
        exit 1
      fi
      certbot certonly \
        --standalone \
        --email "$CERTBOT_EMAIL" \
        --agree-tos \
        --non-interactive \
        --domain "$TLS_DOMAIN" \
        --preferred-challenges http
      # Copy certs (not symlinks) so the nginx container can read them from
      # the bind-mounted /opt/octowatch/ssl without needing /etc/letsencrypt.
      cp "/etc/letsencrypt/live/$TLS_DOMAIN/fullchain.pem" "$SSL_DIR/cert.pem"
      cp "/etc/letsencrypt/live/$TLS_DOMAIN/privkey.pem"   "$SSL_DIR/key.pem"
      echo "[cloud-init] Let's Encrypt certificate provisioned for $TLS_DOMAIN."
    else
      # Self-signed: generate a certificate valid for 10 years.
      echo "[cloud-init] Generating self-signed certificate for $TLS_DOMAIN..."
      openssl req \
        -x509 \
        -nodes \
        -newkey rsa:4096 \
        -keyout "$SSL_DIR/key.pem" \
        -out    "$SSL_DIR/cert.pem" \
        -days   3650 \
        -subj   "/CN=$TLS_DOMAIN/O=OctoWatch/C=US" \
        -addext "subjectAltName=DNS:$TLS_DOMAIN"
      echo "[cloud-init] Self-signed certificate generated."
    fi

    chmod 644 "$SSL_DIR/key.pem"
    chmod 644 "$SSL_DIR/cert.pem"
    chown root:root "$SSL_DIR/key.pem" "$SSL_DIR/cert.pem"

  # -- Step 11: Pull Docker images from GHCR ------------------------------------
  - |
    set -eu
    echo "[cloud-init] Pulling Docker images..."
    cd /opt/octowatch/compose
    docker compose pull
    echo "[cloud-init] Docker images pulled."

  # -- Step 12: Start the Docker Compose stack -----------------------------------
  - |
    set -eu
    echo "[cloud-init] Starting OctoWatch stack..."
    cd /opt/octowatch/compose
    docker compose up -d --remove-orphans
    echo "[cloud-init] OctoWatch stack started."

  # -- Step 13: Enable and start the systemd service ----------------------------
  - |
    set -eu
    systemctl daemon-reload
    systemctl enable octowatch.service
    echo "[cloud-init] octowatch.service enabled."

  # -- Step 14: Set up cron jobs -------------------------------------------------
  # Cron files and scripts are written by write_files above (avoids YAML parse
  # failures caused by zero-indented heredoc content in literal block scalars).
  - |
    set -eu
    chmod 644 /etc/cron.d/octowatch-backup
    chmod 644 /etc/cron.d/octowatch-certbot
    chmod 755 /opt/octowatch/scripts/renew-cert.sh
    echo "[cloud-init] Cron jobs and renewal script ready."

  # -- Step 15: Final health check and log --------------------------------------
  - |
    set -eu
    echo "[cloud-init] Waiting 30s for containers to reach healthy state..."
    sleep 30
    cd /opt/octowatch/compose
    docker compose ps
    echo "[cloud-init] OctoWatch bootstrap complete. Environment: ${environment}"

final_message: |
  OctoWatch bootstrap complete.
  Environment: ${environment}
  Domain: ${tls_domain}
  TLS mode: ${tls_mode}
  Check logs: journalctl -u cloud-final -f
  Stack status: docker compose -f /opt/octowatch/compose/docker-compose.yml ps
