#cloud-config
# OctoWatch K8s Node Bootstrap — Ubuntu 24.04 LTS
# Role: ${role} | Node: ${node_name}
# Generated by Terraform — do not edit on the VM.

package_update: true
package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - jq
  - socat
  - conntrack

write_files:

  # ── Kernel modules for K8s networking ──────────────────────────────────────
  - path: /etc/modules-load.d/k8s.conf
    owner: root:root
    permissions: '0644'
    content: |
      overlay
      br_netfilter

  # ── Sysctl tuning for K8s ─────────────────────────────────────────────────
  - path: /etc/sysctl.d/k8s.conf
    owner: root:root
    permissions: '0644'
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1

  # ── SSH hardening ─────────────────────────────────────────────────────────
  - path: /etc/ssh/sshd_config.d/99-octowatch.conf
    owner: root:root
    permissions: '0600'
    content: |
      PasswordAuthentication no
      PermitRootLogin no
      PubkeyAuthentication yes
      MaxAuthTries 3
      LoginGraceTime 30
      ClientAliveInterval 300
      ClientAliveCountMax 2
      X11Forwarding no
      AllowAgentForwarding yes
      AllowTcpForwarding no

  # ── containerd config (SystemdCgroup = true) ──────────────────────────────
  - path: /etc/containerd/config.toml
    owner: root:root
    permissions: '0644'
    content: |
      version = 2

      [plugins."io.containerd.grpc.v1.cri"]
        sandbox_image = "registry.k8s.io/pause:3.10"
        [plugins."io.containerd.grpc.v1.cri".containerd]
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
            runtime_type = "io.containerd.runc.v2"
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
              SystemdCgroup = true

  # ── kubeadm config (control-plane only) ───────────────────────────────────
%{ if role == "control-plane" }
  - path: /etc/kubernetes/kubeadm-config.yaml
    owner: root:root
    permissions: '0600'
    content: |
      apiVersion: kubeadm.k8s.io/v1beta3
      kind: InitConfiguration
      localAPIEndpoint:
        advertiseAddress: "${private_ip}"
        bindPort: 6443
      nodeRegistration:
        name: "${node_name}"
      ---
      apiVersion: kubeadm.k8s.io/v1beta3
      kind: ClusterConfiguration
      kubernetesVersion: "v${k8s_version}"
      controlPlaneEndpoint: "${private_ip}:6443"
      networking:
        podSubnet: "${pod_cidr}"
        serviceSubnet: "10.96.0.0/12"
      ---
      apiVersion: kubelet.config.k8s.io/v1beta1
      kind: KubeletConfiguration
      cgroupDriver: systemd
%{ endif }

runcmd:

  # ── Disable swap ──────────────────────────────────────────────────────────
  - swapoff -a
  - sed -i '/swap/d' /etc/fstab

  # ── Load kernel modules ───────────────────────────────────────────────────
  - modprobe overlay
  - modprobe br_netfilter
  - sysctl --system

  # ── Format and mount data disk ────────────────────────────────────────────
  - |
    MOUNT_POINT="/mnt/octowatch-data"
    DATA_DISK=""

    # Wait for data disk to appear (supports both SCSI and NVMe paths)
    for i in $(seq 1 60); do
      # Try SCSI path first (v4/v5 VMs)
      if [ -e "/dev/disk/azure/scsi1/lun0" ]; then
        DATA_DISK=$(readlink -f /dev/disk/azure/scsi1/lun0)
        echo "Found data disk (SCSI): $DATA_DISK"
        break
      fi
      # Try NVMe path (v6+ VMs) — find unpartitioned NVMe disk that isn't the OS disk
      for dev in /dev/nvme*n1; do
        # Skip if it's the OS disk (has partitions)
        if [ -e "$${dev}p1" ]; then
          continue
        fi
        # Found an unpartitioned NVMe disk — this is our data disk
        DATA_DISK="$dev"
        echo "Found data disk (NVMe): $DATA_DISK"
        break 2
      done
      echo "Waiting for data disk ($i/60)..."
      sleep 5
    done

    if [ -z "$DATA_DISK" ]; then
      echo "ERROR: No data disk found after 5 minutes"
      exit 1
    fi

    if ! blkid "$DATA_DISK" | grep -q ext4; then
      mkfs.ext4 -F "$DATA_DISK"
    fi
    mkdir -p "$MOUNT_POINT"
    # Use UUID for stable fstab entry
    DISK_UUID=$(blkid -s UUID -o value "$DATA_DISK")
    if ! grep -q "$MOUNT_POINT" /etc/fstab; then
      echo "UUID=$DISK_UUID $MOUNT_POINT ext4 defaults,nofail 0 2" >> /etc/fstab
    fi
    mount -a

  # ── Install containerd ────────────────────────────────────────────────────
  - |
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
      gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
    echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] \
      https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
      > /etc/apt/sources.list.d/docker.list
    apt-get update
    apt-get install -y containerd.io
    mkdir -p /etc/containerd
    systemctl restart containerd
    systemctl enable containerd

  # ── Install kubeadm, kubelet, kubectl ─────────────────────────────────────
  - |
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL "https://pkgs.k8s.io/core:/stable:/v${k8s_version}/deb/Release.key" | \
      gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] \
      https://pkgs.k8s.io/core:/stable:/v${k8s_version}/deb/ /" \
      > /etc/apt/sources.list.d/kubernetes.list
    apt-get update
    apt-get install -y kubelet kubeadm kubectl
    apt-mark hold kubelet kubeadm kubectl
    systemctl enable kubelet

  # ── Install Azure CLI (for bootstrap token exchange) ──────────────────────
  - |
    curl -sL https://aka.ms/InstallAzureCLIDeb | bash

  # ── Set hostname ──────────────────────────────────────────────────────────
  - hostnamectl set-hostname "${node_name}"

%{ if role == "control-plane" }
  # ══════════════════════════════════════════════════════════════════════════
  # CONTROL-PLANE: kubeadm init + Flannel + upload bootstrap artifacts
  # ══════════════════════════════════════════════════════════════════════════

  - |
    echo "Starting kubeadm init..."
    kubeadm init --config=/etc/kubernetes/kubeadm-config.yaml 2>&1 | tee /var/log/kubeadm-init.log

    # Setup kubectl for root
    mkdir -p /root/.kube
    cp /etc/kubernetes/admin.conf /root/.kube/config
    export KUBECONFIG=/etc/kubernetes/admin.conf

    # Untaint control-plane so workloads can schedule on it
    kubectl taint nodes --all node-role.kubernetes.io/control-plane- 2>/dev/null || true

    # Install Flannel CNI (pinned version)
    kubectl apply -f https://github.com/flannel-io/flannel/releases/download/v0.26.1/kube-flannel.yml

    # Wait for node to be Ready
    for i in $(seq 1 60); do
      STATUS=$(kubectl get node "${node_name}" -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}' 2>/dev/null || echo "Unknown")
      echo "Node status: $STATUS ($i/60)"
      [ "$STATUS" = "True" ] && break
      sleep 10
    done

    # Generate join command
    JOIN_CMD=$(kubeadm token create --print-join-command)
    echo "$JOIN_CMD" > /tmp/join-command.txt

    # Upload join command to Azure Blob
    az storage blob upload \
      --account-name "${storage_account_name}" \
      --account-key "${storage_account_key}" \
      --container-name "k8s-bootstrap" \
      --name "join-command.txt" \
      --file /tmp/join-command.txt \
      --overwrite \
      --only-show-errors

    # Upload admin kubeconfig
    az storage blob upload \
      --account-name "${storage_account_name}" \
      --account-key "${storage_account_key}" \
      --container-name "k8s-bootstrap" \
      --name "admin.conf" \
      --file /etc/kubernetes/admin.conf \
      --overwrite \
      --only-show-errors

    rm -f /tmp/join-command.txt
    echo "Control-plane bootstrap complete. Join command + kubeconfig uploaded to blob."
%{ endif }

%{ if role == "worker" }
  # ══════════════════════════════════════════════════════════════════════════
  # WORKER: wait for join command, then kubeadm join
  # ══════════════════════════════════════════════════════════════════════════

  - |
    echo "Waiting for join command from control-plane..."
    for i in $(seq 1 90); do
      az storage blob download \
        --account-name "${storage_account_name}" \
        --account-key "${storage_account_key}" \
        --container-name "k8s-bootstrap" \
        --name "join-command.txt" \
        --file /tmp/join-command.txt \
        --only-show-errors 2>/dev/null && break
      echo "Waiting for join command... ($i/90)"
      sleep 10
    done

    if [ ! -f /tmp/join-command.txt ]; then
      echo "ERROR: Join command not available after 15 minutes"
      exit 1
    fi

    JOIN_CMD=$(cat /tmp/join-command.txt)
    echo "Joining cluster: $JOIN_CMD"
    $JOIN_CMD --node-name="${node_name}" 2>&1 | tee /var/log/kubeadm-join.log

    rm -f /tmp/join-command.txt
    echo "Worker node joined cluster successfully."
%{ endif }

final_message: "OctoWatch K8s ${role} node ${node_name} bootstrap complete."
