#cloud-config
# OctoWatch cloud-init bootstrap for Ubuntu 24.04 LTS
# Environment: ${environment}
# Generated by Terraform — do not edit on the VM.

package_update: true
package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - jq
  - git
  - unzip
  - python3-pip
  - certbot
  - postgresql-client

write_files:

  # ── Docker daemon configuration ──────────────────────────────────────────────
  # - JSON log driver with rotation (max 100 MB × 3 files)
  # - live-restore: containers keep running during daemon upgrades
  # - userns-remap: run containers as unprivileged user namespace (defence-in-depth)
  # - no-new-privileges: prevent privilege escalation inside containers
  - path: /etc/docker/daemon.json
    owner: root:root
    permissions: '0644'
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m",
          "max-file": "3"
        },
        "live-restore": true,
        "userns-remap": "default",
        "no-new-privileges": true
      }

  # ── SSH hardening ─────────────────────────────────────────────────────────────
  - path: /etc/ssh/sshd_config.d/99-octowatch.conf
    owner: root:root
    permissions: '0600'
    content: |
      # OctoWatch SSH hardening — managed by cloud-init
      PasswordAuthentication no
      PermitRootLogin no
      PubkeyAuthentication yes
      AuthorizedKeysFile .ssh/authorized_keys
      MaxAuthTries 3
      LoginGraceTime 30
      ClientAliveInterval 300
      ClientAliveCountMax 2
      X11Forwarding no
      AllowAgentForwarding no
      AllowTcpForwarding no
      PermitTunnel no
      Banner none

  # ── Systemd service unit ──────────────────────────────────────────────────────
  # Starts the Docker Compose stack on boot after docker.service is ready.
  - path: /etc/systemd/system/octowatch.service
    owner: root:root
    permissions: '0644'
    content: |
      [Unit]
      Description=OctoWatch Docker Compose Stack
      Documentation=https://github.com/${ghcr_owner}/octowatch
      Requires=docker.service
      After=docker.service network-online.target

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      WorkingDirectory=/opt/octowatch/compose
      ExecStart=/usr/bin/docker compose up -d --remove-orphans
      ExecStop=/usr/bin/docker compose down --timeout 30
      User=root
      StandardOutput=journal
      StandardError=journal
      TimeoutStartSec=300

      [Install]
      WantedBy=multi-user.target

  # ── PostgreSQL backup script ──────────────────────────────────────────────────
  # Runs from cron (daily at 03:00 UTC). Uses managed identity for Azure auth.
  # Requires: pg_dump installed (postgresql-client package), az CLI.
  - path: /opt/octowatch/scripts/backup-azure.sh
    owner: root:root
    permissions: '0750'
    content: |
      #!/bin/bash
      # OctoWatch — PostgreSQL backup to Azure Blob Storage
      # Authenticates via VM managed identity (no stored credentials).
      set -euo pipefail

      STORAGE_ACCOUNT="${storage_account_name}"
      CONTAINER="pg-backups"
      LOG_PREFIX="[octowatch-backup]"
      BACKUP_DATE=$(date +%Y%m%d-%H%M%S)
      BLOB_PATH="$(date +%Y/%m/%d)/$BACKUP_DATE.sql.gz"
      BACKUP_FILE="/tmp/octowatch-$BACKUP_DATE.sql.gz"

      echo "$LOG_PREFIX Starting backup: $BACKUP_DATE"

      # Load application environment (DATABASE_URL etc.)
      if [ -f /opt/octowatch/compose/.env ]; then
        set -a
        # shellcheck disable=SC1091
        source /opt/octowatch/compose/.env
        set +a
      else
        echo "$LOG_PREFIX ERROR: .env file not found" >&2
        exit 1
      fi

      if [ -z "$${DATABASE_URL:-}" ]; then
        echo "$LOG_PREFIX ERROR: DATABASE_URL is not set" >&2
        exit 1
      fi

      # Dump the PostgreSQL database and compress inline.
      echo "$LOG_PREFIX Dumping database..."
      pg_dump "$DATABASE_URL" | gzip > "$BACKUP_FILE"
      BACKUP_SIZE=$(du -sh "$BACKUP_FILE" | cut -f1)
      echo "$LOG_PREFIX Dump complete: $BACKUP_SIZE"

      # Upload to Azure Blob Storage using managed identity.
      echo "$LOG_PREFIX Uploading to Azure Blob Storage: $BLOB_PATH"
      az storage blob upload \
        --account-name "$STORAGE_ACCOUNT" \
        --container-name "$CONTAINER" \
        --name "$BLOB_PATH" \
        --file "$BACKUP_FILE" \
        --auth-mode login \
        --overwrite

      # Clean up local temp file.
      rm -f "$BACKUP_FILE"

      echo "$LOG_PREFIX Backup completed successfully: gs://$STORAGE_ACCOUNT/$CONTAINER/$BLOB_PATH"

  # ── nginx.conf (base64-encoded from repo source) ──────────────────────────────
  - path: /opt/octowatch/nginx/nginx.conf
    owner: root:root
    permissions: '0644'
    encoding: b64
    content: ${nginx_conf_b64}

  # ── docker-compose.yml (base64-encoded, GHCR images + bind-mount volumes) ─────
  # The compose file has been modified from the repo source:
  #   - Image names updated to ghcr.io/${ghcr_owner}/octowatch-*:${ghcr_image_tag}
  #   - Top-level volumes replaced with bind-mount entries pointing to the data disk
  #   - nginx volume paths updated to absolute host paths
  - path: /opt/octowatch/compose/docker-compose.yml
    owner: root:root
    permissions: '0644'
    encoding: b64
    content: ${compose_b64}

runcmd:

  # ── Step 1: Install Docker CE from the official apt repository ────────────────
  # We install docker-ce (not docker.io) to get the latest stable release with
  # compose plugin support.
  - |
    set -euo pipefail
    echo "[cloud-init] Installing Docker CE..."
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
      -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc
    ARCH=$(dpkg --print-architecture)
    CODENAME=$(. /etc/os-release && echo "$VERSION_CODENAME")
    echo "deb [arch=$ARCH signed-by=/etc/apt/keyrings/docker.asc] \
    https://download.docker.com/linux/ubuntu $CODENAME stable" \
      > /etc/apt/sources.list.d/docker.list
    apt-get update -qq
    apt-get install -y \
      docker-ce \
      docker-ce-cli \
      containerd.io \
      docker-buildx-plugin \
      docker-compose-plugin
    systemctl enable docker
    systemctl start docker
    echo "[cloud-init] Docker CE installed: $(docker --version)"

  # ── Step 2: Install Azure CLI ─────────────────────────────────────────────────
  - |
    set -euo pipefail
    echo "[cloud-init] Installing Azure CLI..."
    curl -sL https://aka.ms/InstallAzureCLIDeb | bash
    echo "[cloud-init] Azure CLI installed: $(az --version | head -1)"

  # ── Step 3: Create octowatch system user and add to docker group ──────────────
  - |
    set -euo pipefail
    echo "[cloud-init] Creating octowatch user..."
    if ! id octowatch &>/dev/null; then
      useradd \
        --system \
        --create-home \
        --home-dir /home/octowatch \
        --shell /bin/bash \
        --comment "OctoWatch service account" \
        octowatch
    fi
    usermod -aG docker octowatch
    echo "[cloud-init] User octowatch created and added to docker group."

  # ── Step 4: Create application directory structure ────────────────────────────
  - |
    set -euo pipefail
    echo "[cloud-init] Creating directory structure..."
    mkdir -p \
      /opt/octowatch/compose \
      /opt/octowatch/nginx \
      /opt/octowatch/ssl \
      /opt/octowatch/certbot-webroot \
      /opt/octowatch/scripts
    # Data disk subdirectories (will exist after disk mount in Step 5)
    # Created here as placeholders; Step 5 recreates them on the mounted volume.
    mkdir -p \
      /mnt/octowatch-data/pg_data \
      /mnt/octowatch-data/valkey_data
    chown -R octowatch:octowatch /opt/octowatch
    chmod 750 /opt/octowatch/scripts
    echo "[cloud-init] Directory structure created."

  # ── Step 5: Format and mount data disk ───────────────────────────────────────
  # Azure attaches the first data disk (LUN 0) as /dev/sdc on Ubuntu 24.04.
  # We format it ext4 and add a permanent fstab entry with nofail so the VM
  # boots cleanly even if the disk is temporarily detached.
  - |
    set -euo pipefail
    DATA_DISK="/dev/sdc"
    MOUNT_POINT="/mnt/octowatch-data"
    echo "[cloud-init] Preparing data disk $DATA_DISK..."

    # Wait up to 60 seconds for the disk to appear (udev timing).
    WAITED=0
    while [ ! -b "$DATA_DISK" ] && [ $WAITED -lt 60 ]; do
      echo "[cloud-init] Waiting for $DATA_DISK... ($WAITED s)"
      sleep 5
      WAITED=$((WAITED + 5))
    done

    if [ ! -b "$DATA_DISK" ]; then
      echo "[cloud-init] ERROR: Data disk $DATA_DISK not found after 60s" >&2
      exit 1
    fi

    # Format only if the disk has no filesystem (idempotent).
    FS_TYPE=$(blkid -o value -s TYPE "$DATA_DISK" 2>/dev/null || echo "")
    if [ -z "$FS_TYPE" ]; then
      echo "[cloud-init] Formatting $DATA_DISK as ext4..."
      mkfs.ext4 -L octowatch-data -F "$DATA_DISK"
    else
      echo "[cloud-init] $DATA_DISK already has filesystem: $FS_TYPE — skipping format."
    fi

    # Mount the data disk.
    mkdir -p "$MOUNT_POINT"
    mount "$DATA_DISK" "$MOUNT_POINT"

    # Add fstab entry (nofail ensures boot continues if disk is absent).
    DISK_UUID=$(blkid -s UUID -o value "$DATA_DISK")
    if ! grep -q "$DISK_UUID" /etc/fstab; then
      echo "UUID=$DISK_UUID  $MOUNT_POINT  ext4  defaults,nofail,noatime  0  2" >> /etc/fstab
      echo "[cloud-init] Added fstab entry for UUID=$DISK_UUID"
    fi

    # Create Docker volume bind-mount directories on the data disk.
    mkdir -p \
      "$MOUNT_POINT/pg_data" \
      "$MOUNT_POINT/valkey_data"
    chown -R 999:999 "$MOUNT_POINT/pg_data"   # PostgreSQL UID
    chown -R 999:999 "$MOUNT_POINT/valkey_data"
    chmod 700 "$MOUNT_POINT/pg_data"
    echo "[cloud-init] Data disk mounted at $MOUNT_POINT."

  # ── Step 6: Authenticate to Azure via managed identity ────────────────────────
  - |
    set -euo pipefail
    echo "[cloud-init] Logging in to Azure via managed identity..."
    # Retry loop: the IMDS endpoint may not be ready immediately after boot.
    for i in 1 2 3 4 5; do
      if az login --identity --username "${managed_identity_client_id}" --output none 2>/dev/null; then
        echo "[cloud-init] Azure login successful."
        break
      fi
      echo "[cloud-init] Azure login attempt $i failed, retrying in 15s..."
      sleep 15
    done
    az account show --output none || { echo "[cloud-init] ERROR: Azure login failed"; exit 1; }

  # ── Step 7: Fetch secrets from Key Vault and write .env file ─────────────────
  # All secrets are read from Azure Key Vault using the VM managed identity.
  # The .env file is written to /opt/octowatch/compose/.env (chmod 600).
  - |
    set -euo pipefail
    VAULT="${key_vault_name}"
    ENV_FILE="/opt/octowatch/compose/.env"

    echo "[cloud-init] Fetching secrets from Key Vault: $VAULT"

    # Helper: fetch a secret by name; return empty string on failure.
    get_secret() {
      az keyvault secret show \
        --vault-name "$VAULT" \
        --name "$1" \
        --query "value" \
        --output tsv 2>/dev/null || echo ""
    }

    # Fetch all secrets.
    DATABASE_URL=$(get_secret "octowatch-database-url")
    SECRET_KEY=$(get_secret "octowatch-secret-key")
    ENCRYPTION_KEY=$(get_secret "octowatch-encryption-key")
    VALKEY_URL=$(get_secret "octowatch-valkey-url")
    VALKEY_PASSWORD=$(get_secret "octowatch-valkey-password")
    POSTGRES_USER=$(get_secret "octowatch-postgres-user")
    POSTGRES_PASSWORD=$(get_secret "octowatch-postgres-password")
    POSTGRES_DB=$(get_secret "octowatch-postgres-db")
    GITHUB_CLIENT_ID=$(get_secret "octowatch-github-client-id")
    GITHUB_CLIENT_SECRET=$(get_secret "octowatch-github-client-secret")
    GITHUB_RULES_REPO=$(get_secret "octowatch-github-rules-repo")
    GITHUB_RULES_TOKEN=$(get_secret "octowatch-github-rules-token")
    INITIAL_ADMIN_LOGINS=$(get_secret "octowatch-initial-admin-logins")
    APP_BASE_URL=$(get_secret "octowatch-app-base-url")
    GHCR_TOKEN=$(get_secret "octowatch-ghcr-token")
    GITHUB_APP_ID=$(get_secret "octowatch-github-app-id")
    GITHUB_APP_PRIVATE_KEY=$(get_secret "octowatch-github-app-private-key")
    GITHUB_ENTERPRISE_SLUG=$(get_secret "octowatch-github-enterprise-slug")
    MAXMIND_LICENSE_KEY=$(get_secret "octowatch-maxmind-license-key")
    OKTA_ORG_URL=$(get_secret "octowatch-okta-org-url")
    OKTA_API_TOKEN=$(get_secret "octowatch-okta-api-token")
    AZURE_AD_TENANT_ID=$(get_secret "octowatch-azure-ad-tenant-id")
    AZURE_AD_CLIENT_ID=$(get_secret "octowatch-azure-ad-client-id")
    AZURE_AD_CLIENT_SECRET=$(get_secret "octowatch-azure-ad-client-secret")
    SLACK_BOT_TOKEN=$(get_secret "octowatch-slack-bot-token")
    SMTP_HOST=$(get_secret "octowatch-smtp-host")
    SMTP_USERNAME=$(get_secret "octowatch-smtp-username")
    SMTP_PASSWORD=$(get_secret "octowatch-smtp-password")
    JIRA_URL=$(get_secret "octowatch-jira-url")
    JIRA_USERNAME=$(get_secret "octowatch-jira-username")
    JIRA_API_TOKEN=$(get_secret "octowatch-jira-api-token")

    # Write GitHub App private key to a dedicated file if provided.
    GITHUB_APP_PRIVATE_KEY_PATH=""
    if [ -n "$GITHUB_APP_PRIVATE_KEY" ]; then
      KEY_FILE="/opt/octowatch/compose/github-app-key.pem"
      printf '%s\n' "$GITHUB_APP_PRIVATE_KEY" > "$KEY_FILE"
      chmod 600 "$KEY_FILE"
      chown octowatch:octowatch "$KEY_FILE"
      GITHUB_APP_PRIVATE_KEY_PATH="$KEY_FILE"
      echo "[cloud-init] GitHub App private key written to $KEY_FILE"
    fi

    # Write .env file (chmod 600 — secrets at rest).
    cat > "$ENV_FILE" <<ENVEOF
# OctoWatch environment — generated at boot from Azure Key Vault
# DO NOT edit manually; re-provision via Terraform to change secrets.
# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)

# ── Core ──────────────────────────────────────────────────────────────────────
DATABASE_URL=$DATABASE_URL
SECRET_KEY=$SECRET_KEY
ENCRYPTION_KEY=$ENCRYPTION_KEY
VALKEY_URL=$VALKEY_URL
VALKEY_PASSWORD=$VALKEY_PASSWORD

# ── PostgreSQL ────────────────────────────────────────────────────────────────
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=$POSTGRES_DB

# ── GitHub OAuth & Rules ──────────────────────────────────────────────────────
GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID
GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET
GITHUB_RULES_REPO=$GITHUB_RULES_REPO
GITHUB_RULES_TOKEN=$GITHUB_RULES_TOKEN

# ── Application ───────────────────────────────────────────────────────────────
APP_BASE_URL=$APP_BASE_URL
INITIAL_ADMIN_LOGINS=$INITIAL_ADMIN_LOGINS
INGESTION_MODE=hec
LOG_LEVEL=INFO

# ── GitHub App (Enterprise Sync) ──────────────────────────────────────────────
GITHUB_APP_ID=$GITHUB_APP_ID
GITHUB_APP_PRIVATE_KEY_PATH=$GITHUB_APP_PRIVATE_KEY_PATH
GITHUB_ENTERPRISE_SLUG=$GITHUB_ENTERPRISE_SLUG
GITHUB_SYNC_ENABLED=false

# ── MaxMind GeoIP ─────────────────────────────────────────────────────────────
MAXMIND_LICENSE_KEY=$MAXMIND_LICENSE_KEY

# ── Okta IdP ──────────────────────────────────────────────────────────────────
OKTA_ORG_URL=$OKTA_ORG_URL
OKTA_API_TOKEN=$OKTA_API_TOKEN

# ── Azure AD / Entra IdP ──────────────────────────────────────────────────────
AZURE_AD_TENANT_ID=$AZURE_AD_TENANT_ID
AZURE_AD_CLIENT_ID=$AZURE_AD_CLIENT_ID
AZURE_AD_CLIENT_SECRET=$AZURE_AD_CLIENT_SECRET

# ── Slack Notifications ───────────────────────────────────────────────────────
SLACK_BOT_TOKEN=$SLACK_BOT_TOKEN

# ── SMTP Notifications ────────────────────────────────────────────────────────
SMTP_HOST=$SMTP_HOST
SMTP_PORT=587
SMTP_USERNAME=$SMTP_USERNAME
SMTP_PASSWORD=$SMTP_PASSWORD
SMTP_FROM_ADDRESS=

# ── Jira Ticketing ────────────────────────────────────────────────────────────
JIRA_URL=$JIRA_URL
JIRA_USERNAME=$JIRA_USERNAME
JIRA_API_TOKEN=$JIRA_API_TOKEN
ENVEOF

    chmod 600 "$ENV_FILE"
    chown octowatch:octowatch "$ENV_FILE"
    echo "[cloud-init] .env file written to $ENV_FILE"

    # Store GHCR token in a variable for Step 9.
    echo "$GHCR_TOKEN" > /opt/octowatch/.ghcr_token
    chmod 600 /opt/octowatch/.ghcr_token

  # ── Step 8: Set correct ownership on compose files ───────────────────────────
  - |
    set -euo pipefail
    chown -R octowatch:octowatch /opt/octowatch/compose
    chown octowatch:octowatch /opt/octowatch/nginx/nginx.conf
    echo "[cloud-init] File ownership set."

  # ── Step 9: Authenticate to GHCR ─────────────────────────────────────────────
  - |
    set -euo pipefail
    echo "[cloud-init] Logging in to GHCR..."
    GHCR_TOKEN=$(cat /opt/octowatch/.ghcr_token)
    echo "$GHCR_TOKEN" | docker login ghcr.io \
      --username "${ghcr_username}" \
      --password-stdin
    rm -f /opt/octowatch/.ghcr_token
    echo "[cloud-init] GHCR login successful."

  # ── Step 10: TLS certificate provisioning ────────────────────────────────────
  # Mode: ${tls_mode}
  # Domain: ${tls_domain}
  - |
    set -euo pipefail
    TLS_MODE="${tls_mode}"
    TLS_DOMAIN="${tls_domain}"
    SSL_DIR="/opt/octowatch/ssl"
    CERTBOT_WEBROOT="/opt/octowatch/certbot-webroot"

    echo "[cloud-init] Provisioning TLS certificates (mode: $TLS_MODE, domain: $TLS_DOMAIN)..."

    if [ "$TLS_MODE" = "letsencrypt" ]; then
      # Let's Encrypt: use certbot with webroot authenticator.
      # nginx must serve /.well-known/acme-challenge/ from $CERTBOT_WEBROOT.
      # We start a temporary HTTP-only nginx to serve the challenge before
      # the main stack is up.
      CERTBOT_EMAIL="${certbot_email}"
      if [ -z "$CERTBOT_EMAIL" ]; then
        echo "[cloud-init] ERROR: certbot_email is required for letsencrypt mode" >&2
        exit 1
      fi
      certbot certonly \
        --webroot \
        --webroot-path "$CERTBOT_WEBROOT" \
        --email "$CERTBOT_EMAIL" \
        --agree-tos \
        --non-interactive \
        --domain "$TLS_DOMAIN" \
        --preferred-challenges http
      # Symlink Let's Encrypt certs to the expected location.
      ln -sf "/etc/letsencrypt/live/$TLS_DOMAIN/fullchain.pem" "$SSL_DIR/cert.pem"
      ln -sf "/etc/letsencrypt/live/$TLS_DOMAIN/privkey.pem"   "$SSL_DIR/key.pem"
      echo "[cloud-init] Let's Encrypt certificate provisioned for $TLS_DOMAIN."
    else
      # Self-signed: generate a certificate valid for 10 years.
      echo "[cloud-init] Generating self-signed certificate for $TLS_DOMAIN..."
      openssl req \
        -x509 \
        -nodes \
        -newkey rsa:4096 \
        -keyout "$SSL_DIR/key.pem" \
        -out    "$SSL_DIR/cert.pem" \
        -days   3650 \
        -subj   "/CN=$TLS_DOMAIN/O=OctoWatch/C=US" \
        -addext "subjectAltName=DNS:$TLS_DOMAIN"
      echo "[cloud-init] Self-signed certificate generated."
    fi

    chmod 600 "$SSL_DIR/key.pem"
    chmod 644 "$SSL_DIR/cert.pem"
    chown root:root "$SSL_DIR/key.pem" "$SSL_DIR/cert.pem"

  # ── Step 11: Pull Docker images from GHCR ────────────────────────────────────
  - |
    set -euo pipefail
    echo "[cloud-init] Pulling Docker images..."
    cd /opt/octowatch/compose
    docker compose pull
    echo "[cloud-init] Docker images pulled."

  # ── Step 12: Start the Docker Compose stack ───────────────────────────────────
  - |
    set -euo pipefail
    echo "[cloud-init] Starting OctoWatch stack..."
    cd /opt/octowatch/compose
    docker compose up -d --remove-orphans
    echo "[cloud-init] OctoWatch stack started."

  # ── Step 13: Enable and start the systemd service ────────────────────────────
  - |
    set -euo pipefail
    systemctl daemon-reload
    systemctl enable octowatch.service
    echo "[cloud-init] octowatch.service enabled."

  # ── Step 14: Set up cron jobs ─────────────────────────────────────────────────
  - |
    set -euo pipefail

    # Daily PostgreSQL backup at 03:00 UTC.
    cat > /etc/cron.d/octowatch-backup <<'CRONEOF'
    # OctoWatch — daily PostgreSQL backup to Azure Blob Storage
    0 3 * * * root /opt/octowatch/scripts/backup-azure.sh >> /var/log/octowatch-backup.log 2>&1
    CRONEOF
    chmod 644 /etc/cron.d/octowatch-backup
    echo "[cloud-init] Backup cron installed."

    # Let's Encrypt certificate renewal (only when tls_mode=letsencrypt).
    TLS_MODE="${tls_mode}"
    TLS_DOMAIN="${tls_domain}"
    if [ "$TLS_MODE" = "letsencrypt" ]; then
      cat > /etc/cron.d/octowatch-certbot <<CRONEOF
    # OctoWatch — Let's Encrypt renewal check (twice daily per certbot best practice)
    0 */12 * * * root certbot renew --quiet --webroot \
      --webroot-path /opt/octowatch/certbot-webroot \
      --post-hook 'cd /opt/octowatch/compose && docker compose exec nginx nginx -s reload' \
      >> /var/log/letsencrypt/renewal.log 2>&1
    CRONEOF
      chmod 644 /etc/cron.d/octowatch-certbot
      echo "[cloud-init] Certbot renewal cron installed."
    fi

  # ── Step 15: Final health check and log ──────────────────────────────────────
  - |
    set -euo pipefail
    echo "[cloud-init] Waiting 30s for containers to reach healthy state..."
    sleep 30
    cd /opt/octowatch/compose
    docker compose ps
    echo "[cloud-init] OctoWatch bootstrap complete. Environment: ${environment}"

final_message: |
  OctoWatch bootstrap complete.
  Environment: ${environment}
  Domain: ${tls_domain}
  TLS mode: ${tls_mode}
  Check logs: journalctl -u cloud-final -f
  Stack status: docker compose -f /opt/octowatch/compose/docker-compose.yml ps
